version: '3.8'

services:
  db:
    image: postgres:15
    container_name: diploma_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-diploma}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  app:
    build: .
    command: sh -c "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    container_name: diploma_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        - VITE_API_URL=${VITE_API_URL:-http://127.0.0.1:8000/api}
    container_name: diploma_frontend
    restart: unless-stopped
    ports:
      - "5173:80"
    env_file:
      - .env
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://127.0.0.1:8000/api}
    depends_on:
      - app

volumes:
  postgres_data: