# Generated by Django 5.2.13 on 2026-04-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='inline_comments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
